security.protocol=SASL_SSL
sasl.mechanism=GSSAPI
sasl.kerberos.service.name=controller
ssl.truststore.location=/opt/kafka/config/jks/controller1.truststore.jks
ssl.truststore.password=cagri3541
sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required \
   useKeyTab=true \
   storeKey=true \
   useTicketCache=false \
   keyTab="/opt/kafka/config/keytabs/controller1.keytab" \
   principal="controller/controller1.dahbest.kfn@DAHBEST.KFN";