# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

############################# KRaft Controller Mode Settings #####################
##################################################################################

############################# Server Basics ######################################
# Basic KRaft Controller Settings
process.roles=controller
node.id=3001

# KRaft Controller Quorum Mapping
controller.quorum.voters=3001@controller1-a.dahbest.kfn:9093
controller.listener.names=CONTROLLER

############################ Socket Server Settings #############################
# The address the socket server listens on.
listeners=CONTROLLER://0.0.0.0:9093
advertised.listeners=CONTROLLER://controller1-a.dahbest.kfn:9093

# Security Protocol Mapping
listener.security.protocol.map=CONTROLLER:SASL_SSL

############################# Authentication ####################################
# SSL Configuration for Controller
ssl.keystore.location=/opt/kafka/config/jks/controller1-a.keystore.jks
ssl.keystore.password=cagri3541
ssl.key.password=cagri3541
ssl.truststore.location=/opt/kafka/config/jks/controller1-a.truststore.jks
ssl.truststore.password=cagri3541
ssl.truststore.type=PKCS12

# Enable OAUTHBEARER and assign it to the controller protocol
sasl.enabled.mechanisms=OAUTHBEARER
sasl.mechanism.controller.protocol=OAUTHBEARER

# Keycloak Endpoint Configuration for the CONTROLLER listener
listener.name.controller.sasl.oauthbearer.token.endpoint.url=https://keycloak.dahbest.kfn:8443/realms/master/protocol/openid-connect/token
listener.name.controller.sasl.oauthbearer.jwks.endpoint.url=https://keycloak.dahbest.kfn:8443/realms/master/protocol/openid-connect/certs
listener.name.controller.sasl.oauthbearer.expected.audience=kafka
listener.name.controller.sasl.oauthbearer.sub.claim.name=client_id
listener.name.controller.sasl.oauthbearer.client.credentials.client.id=kafka-controller
listener.name.controller.sasl.oauthbearer.client.credentials.client.secret=cTCgOCh39yrevYCf60yIuo7WH1heozWN
listener.name.controller.oauthbearer.sasl.server.callback.handler.class=org.apache.kafka.common.security.oauthbearer.OAuthBearerValidatorCallbackHandler
listener.name.controller.oauthbearer.sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler

# Authorization
authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
super.users=User:kafka-controller;User:kafka-admin
allow.everyone.if.no.acl.found=false

############################# Internal Topics ###################################
min.insync.replicas=2

############################# Log Basics ########################################
metadata.log.dir=/opt/data/metadata
log.dirs=/opt/data/controller
