security.protocol=SASL_SSL
sasl.mechanism=GSSAPI
sasl.kerberos.service.name=broker
ssl.truststore.location=/opt/kafka/config/jks/broker1.truststore.jks
ssl.truststore.password=cagri3541
sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required \
   useKeyTab=true \
   storeKey=true \
   useTicketCache=false \
   keyTab="/opt/kafka/config/keytabs/kafka-admin.keytab" \
   principal="kafka-admin/kafka-admin.dahbest.kfn@DAHBEST.KFN";