KafkaServer {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/opt/kafka/config/keytabs/controller3.keytab"
    principal="controller/controller3.dahbest.kfn@DAHBEST.KFN"
    useTicketCache=false
    debug=true;
};