[kdcdefaults]
    kdc_ports = 88
    kdc_tcp_ports = 88

[realms]
    DAHBEST.KFN = {
        database_module = openldap_ldapconf
        admin_keytab = /etc/krb5kdc/kadm5.keytab
        acl_file = /etc/krb5kdc/kadm5.acl
        key_stash_file = /etc/krb5kdc/stash
        max_life = 24h
        max_renewable_life = 7d
        master_key_type = aes256-cts-hmac-sha1-96
        supported_enctypes = aes256-cts-hmac-sha1-96:normal aes128-cts-hmac-sha1-96:normal
        default_principal_flags = +preauth
    }

[dbmodules]
    openldap_ldapconf = {
        db_library = kldap
        ldap_kerberos_container_dn = cn=kerberos,dc=dahbest,dc=com
        ldap_kdc_dn = cn=admin,dc=dahbest,dc=com
        ldap_kadmind_dn = cn=admin,dc=dahbest,dc=com
        ldap_service_password_file = /etc/krb5kdc/service.keyfile
        ldap_servers = ldap://ldap:389
        ldap_conns_per_server = 5
    }

[logging]
    kdc = FILE:/var/log/krb5kdc.log
    admin_server = FILE:/var/log/kadmin.log