broker.KafkaServer {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   storeKey=true
   keyTab="/opt/kafka/config/keytabs/broker3.keytab"
   principal="broker/broker3.dahbest.kfn@DAHBEST.KFN"
   useTicketCache=false
   debug=false;
   org.apache.kafka.common.security.scram.ScramLoginModule required;
};

broker.KafkaClient {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   storeKey=true
   keyTab="/opt/kafka/config/keytabs/broker3.keytab"
   principal="broker/broker3.dahbest.kfn@DAHBEST.KFN"
   useTicketCache=false
   debug=false;
};

external.KafkaServer {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   storeKey=true
   keyTab="/opt/kafka/config/keytabs/broker3.keytab"
   principal="broker/broker3.dahbest.kfn@DAHBEST.KFN"
   useTicketCache=false
   debug=false;
   org.apache.kafka.common.security.scram.ScramLoginModule required;
};

external.KafkaClient {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   storeKey=true
   keyTab="/opt/kafka/config/keytabs/broker3.keytab"
   principal="broker/broker3.dahbest.kfn@DAHBEST.KFN"
   useTicketCache=false
   debug=false;
};

controller.KafkaServer {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   storeKey=true
   keyTab="/opt/kafka/config/keytabs/broker3.keytab"
   principal="controller/broker3.dahbest.kfn@DAHBEST.KFN"
   useTicketCache=false
   debug=false;
   org.apache.kafka.common.security.scram.ScramLoginModule required;
};

controller.KafkaClient {
   com.sun.security.auth.module.Krb5LoginModule required
   useKeyTab=true
   storeKey=true
   keyTab="/opt/kafka/config/keytabs/broker3.keytab"
   principal="controller/broker3.dahbest.kfn@DAHBEST.KFN"
   useTicketCache=false
   debug=false;
};
