include     /etc/ldap/schema/core.schema
include     /etc/ldap/schema/cosine.schema
include     /etc/ldap/schema/inetorgperson.schema
include     /etc/ldap/schema/nis.schema
include     /etc/ldap/schema/kerberos.schema

pidfile     /run/slapd/slapd.pid
argsfile    /run/slapd/slapd.args

# Ubuntu: modules are compiled in, back_mdb doesn't need explicit loading
# If you still get errors, try: moduleload back_mdb.so
moduleload back_mdb.so

database    mdb
suffix      "dc=dahbest,dc=com"
rootdn      "cn=admin,dc=dahbest,dc=com"
rootpw      {SSHA}ZQZN5V1S6YP0DirSSyginXl+Rk3kFqFc

directory   /var/lib/ldap

loglevel    256

index       objectClass eq
index       krbPrincipalName eq,pres,sub