{
 "title": "Jenkins Dashboard",
 "tags": [
  "Jenkins",
  "Monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_job_count_value", "legendFormat": "Total Jobs" }
   ]
  },
  {
   "title": "Total Executors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_executor_count_value", "legendFormat": "Total Executors" }
   ]
  },
  {
   "title": "Jenkin Failure Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_failure_total ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jenkins Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "default_jenkins_up > 0", "legendFormat": "Jenkins Status" }
   ]
  },
  {
   "title": "Jenkins Uptime",
   "type": "gauge",
   "description": "Total time Jenkins has been running since last restart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_uptime / 60 / 24",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vm_memory_heap_used / 100000000",
     "legendFormat": "Heap Usage"
    }
   ]
  },
  {
   "title": "Build Success Rate Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(default_jenkins_builds_success_build_count_total) / sum(default_jenkins_builds_total_build_count_total)",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Last Build Duration by Job",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_duration_milliseconds / 1000",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "vm_memory_heap_used", "legendFormat": "Heap Memory Used" },
    { "expr": "vm_memory_non_heap_used", "legendFormat": "Non-Heap Memory Used" }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[5m])",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}