# 1. Connection Security
security.protocol=SASL_SSL
sasl.mechanism=OAUTHBEARER
sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
sasl.oauthbearer.token.endpoint.url=https://keycloak.dahbest.kfn:8443/realms/master/protocol/openid-connect/token
sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
sasl.oauthbearer.client.credentials.client.id=kafka-admin
sasl.oauthbearer.client.credentials.client.secret=aTCgOCh39yrevYCf60yIuo7WH1heozWN