{
 "title": "kafka - test",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Brokers Alive",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message in Streaming for Each Broker",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_broker_metrics_count{metric_name=\"MessagesInPerSec\"}[30s])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Size For Each Broker",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_size{topic=\"test\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes In Per Second For Each Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(kafka_server_broker_metrics_count{metric_name=\"BytesInPerSec\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message In Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(kafka_server_broker_metrics_count{metric_name=\"MessagesInPerSec\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}